### ISSUE TITLE
MEGA65: Multi color mode problem

### ISSUE THREAD

**Issue by mteufel** [lgblgblgb/xemu#205] opened 2020-10-13 10:30 UTC
**Describe the bug**
When I am in 64 mode and enter

POKE 53270,PEEK(53270) OR 16

everything is perfekt and I see the result: Switching to multicolor.

When I do the same in 65 Mode, no real change. The color bars on top are changing a bit, but the charset itself does not change, its white. Sometimes as you can see in the screenshot, the whole screen turns white.

**Used version of the project**
I compiled the "hmw" Branch of XEMU, because in this branch the vic 4 work should be integrated

**To Reproduce**
see Description

**Expected behavior**
In 65 I would expect a switch to Multicolor-Mode as in 64 mode. When I do a POKE 53282,7 then I expect that the color changes. In 64 modes this is the case, in 65 mode not.

**Screenshots**
C64 Mode after the poke:
![image](https://user-images.githubusercontent.com/536193/95849342-a4990000-0d4f-11eb-89bc-c4987f7bd4d3.png)
C65 Mode after the poke:
![image](https://user-images.githubusercontent.com/536193/95849482-d5793500-0d4f-11eb-8012-f0ececcfe67e.png)

**Computer/Device (please complete the following information):**

**Additional context**

**Comment by lgblgblgb** [comment] 2020-10-13 11:39
Thanks for the report!

I'm not sure, but at first glance, it can be some combination of modes, ie MCM mode with extended attribute text mode together. As it's OK with "C64 mode" but not in "C65 mode", I have the suspect that the difference is having enabled extended attribute mode, in "C65 mode" but not in "C64 mode". Though it's just my first impression, which can be bad, easily.

**Comment by mteufel** [comment] 2020-10-13 11:43
How can I help to get things clear?

**Comment by lgblgblgb** [comment] 2020-10-13 11:49
Don't worry, these comments here (for example my previous one) is more for "in-group" communication and archive-purposes, etc :) It's not meant that you need to do anything too much :) But, if you have time you can try to disable extended attribute mode and enable MCM after that, if it has the same problem then. Surely, it would be the thing I do, as well, However it's worktime here still, so I can do things like this only later!

**Comment by hernandp** [comment] 2020-10-14 18:40
I'll take this.

**Comment by lgblgblgb** [comment] 2020-10-14 18:47
@hernandp OK, then it's yours, my friend :)

**Comment by lgblgblgb** [comment] 2020-10-14 18:48
Note to myself :) I need to check this in the C65 emulator is well ... hmmm ...

**Comment by hernandp** [comment] 2020-10-23 20:40
@lgblgblgb can you test on your MEGA65 hardware for reference? I checked both xemu branches and we are rendering the same output with different implementations.

**Comment by lgblgblgb** [comment] 2020-10-27 17:57
That's funny. Yes, I should have tried this since ages, sorry about that. But the funny thing:

1. make sure your MEGA65 has monitor connection otherwise it does not produce any image ;)
2. but more seriously now: issuing this causes almost NO visible change at all, BUT a very hard to notice pixel difference ONLY at the end of the colour stripes, where their ends have that 45 degree angle, only pixels there some to have some odd ones, nowhere other on the screen ...

So I assume this may not work on MEGA65 either. Surely, we can't test on a real C65 ...

**Comment by hernandp** [comment] 2020-10-27 18:06
@lgblgblgb  Thank you very much my friend. So both emulators are OK and correctly functioning., ;)

**Comment by lgblgblgb** [comment] 2020-10-27 18:07
Yes, maybe, but it can be a coincidence only, and bug in MEGA65, we may need to signal that really it should be the way it works ... (I mean on MEGA65 as well!!!)

**Comment by hernandp** [comment] 2020-10-27 18:08
I agree, thank you!

**Comment by gardners** [comment] 2020-10-27 20:44
You have to set the BANK in C65 mode, before the poke will work, perhaps?
VIC-III Extended attribute mode + MCM is supposed to work properly, I think. Would be good to know behaviour on a real C65. Ask Carlos to test it, perhaps?

**Comment by mteufel** [comment] 2020-10-27 20:45
Do you mean BANK 128 ?


Von: gardners <notifications@github.com>
Antworten an: lgblgblgb/xemu <reply@reply.github.com>
Datum: Dienstag, 27. Oktober 2020 um 21:44
An: lgblgblgb/xemu <xemu@noreply.github.com>
Cc: Teufel Marc <Marc.Teufel@hama.de>, Author <author@noreply.github.com>
Betreff: Re: [lgblgblgb/xemu] MEGA65: Multi color mode problem (#205)


You have to set the BANK in C65 mode, before the poke will work, perhaps?
VIC-III Extended attribute mode + MCM is supposed to work properly, I think. Would be good to know behaviour on a real C65. Ask Carlos to test it, perhaps?

**Comment by lgblgblgb** [comment] 2020-10-27 21:13
Argh this BANK madness of C65 drives me crazy, it should die!!!!!! Grrr. ;)

**Comment by lgblgblgb** [comment] 2020-11-09 16:23
OK, guys, what's the situation with this bug? Is it really a bug, or "just" the case of the "wonders" of the POKE in C65 mode and the BANK madness ;)

**Comment by mteufel** [comment] 2020-11-09 17:08
I would suggest to close it, even if I not really know at the moment why I doesn’t work.  I am working on a Pixler at the moment (Hires and Multicolor) and I will definately come back to this when I want to show the pixelled pictures in 64 and 65 mode. So if I don’t get it to work I come back to you and then – if necessary – we can re-open this one.

Von: LGB <notifications@github.com>
Antworten an: lgblgblgb/xemu <reply@reply.github.com>
Datum: Montag, 9. November 2020 um 17:24
An: lgblgblgb/xemu <xemu@noreply.github.com>
Cc: Teufel Marc <Marc.Teufel@hama.de>, Author <author@noreply.github.com>
Betreff: Re: [lgblgblgb/xemu] MEGA65: Multi color mode problem (#205)


OK, guys, what's the situation with this bug? Is it really a bug, or "just" the case of the "wonders" of the POKE in C65 mode and the BANK madness ;)

**Comment by gardners** [comment] 2020-11-09 22:49
So, it's not a bug but correct behaviour: Remember MCM only applies to characters that use colour 8 through 15 -- thus the light blue of C64 mode triggers all the chars to go MCM, but the white (colour $01) of C65 basic mode doesn't. But if you change the cursor colour in C65 mode to light blue or any other colour from $08 to $0F, you will see the MCM mode activated for those characters.

So this confirms that it isn't a bug, just one of the strange subtleties of MCM mode working correctly.

**Comment by lgblgblgb** [comment] 2020-11-10 09:27
OK, so I missed the point it seems :-O right then, closing the issue, thanks. Honestly I was not so much aware of MCM behaviour in case of text modes, it seems :-O

**Closed** 2020-11-10 09:28 UTC
Labels: NOT A BUG, target:MEGA65
