### ISSUE TITLE
MEGA65+C65: "Run PRG directly" (PRG memory inject) does not set BASIC pointers resulting various problems

### ISSUE THREAD

**Issue by sausagejohnson** [lgblgblgb/xemu#210] opened 2020-11-20 09:13 UTC
When using the "Run PRG directly" feature of the latest Xemu / MEGA65 on Windows, a slighty longer listing can cause a currupt first line of the listing.

Using the same PRG placed in D81 disk file works perfectly in the emulator.

This is using the Windows binary build: 

INFO: Xemu/MEGA65 20201103152903
https://github.com/lgblgblgb/xemu.git HEAD 4c78b8a80386a8c37ef1fb9cf1e6e4f02b097965
Compiled by: travis@lgb on Linux 5.4.0-1028-gcp at Tue 03 Nov 2020 02:57:36 PM UTC
Built with: gcc-mingw64 9.3-win32 20200320 64LE for win64

**To Reproduce**
Steps to reproduce the behavior. As steps as required, do not try to squeeze
everything into one step.
1. Get sample.txt program
2. Convert to prg using C64List.exe with: C64List sample.txt -prg -ovr
3. Fire up xemu/MEGA65
4. Right click "Run PRG Directly"
5. LIST
6. First line is corrupted
7. Repeat the process again, and change line 15 to: 15 print "test."
8. This one will import just fine.

**Expected behavior**
Longer listings to import in Xemu/MEGA65 without corruption and run as intended. To match the behaviour when a PRG is loaded fine from a D81 disk file.

**Screenshots**
![add-prg-directly](https://user-images.githubusercontent.com/11528721/99783243-47724480-2b6e-11eb-98dd-6fb2c83f96e3.png)

**Computer/Device (please complete the following information):**
 - Device/Platform: Windows 10
 - OS and its version: 10.0.14393

**Additional context**
**Sample listing:**

     5 print"line 20 kills this line."
    10 print "good line."
    15 print "another good line."
    20 c=0
    25 print "the end."

**Sample PRG**

[sample.zip](https://github.com/lgblgblgb/xemu/files/5572531/sample.zip)

**Comment by lgblgblgb** [comment] 2020-11-20 09:26
Thanks for the report! I believe this is a problem caused by not setting the BASIC pointers. I've originally designed this feature to load+run simple machine code stuff, having only a line of BASIC stub. You can see even more interesting problems if you try to edit your "injected" BASIC program, btw. This is a problem now affects the similar functionality also presents in the C65 emulator. Moreover - though I haven't tried - it may affect C65 BASIC programs as well. The fix is simple in theory: setting the BASIC pointers after injecting the BASIC programs into the memory. I have some ideas on that on C64, for C65 mode, it's more a grey area for me, and needs further experiments.

**Comment by lgblgblgb** [comment] 2020-11-20 20:55
Currently I have no idea about BASIC interpreters internals, which pointers should be modified and how ... Trying to find information on the web how internally CBM BASIC works, to store the needed information to be changed.

**Comment by lgblgblgb** [comment] 2020-11-21 08:35
Please do a test if https://github.com/lgblgblgb/xemu-binaries/tree/binary-windows-vic fixes the problem, at least for MEGA65 emulator (not the C65 yet) and only in C64 mode for now. The link above is the direct link, and not the usual one, since not pushed back yet to 'dev' or 'master' which can be accessed at https://github.lgb.hu/xemu/ Since you seemed to use the windows build I quoted that direct link for you here.

**Comment by sausagejohnson** [comment] 2020-11-22 08:46
It works!!! BASIC is loading and appears to be running everything that was failing before.

**Comment by lgblgblgb** [comment] 2020-12-27 00:11
In the "vic" branch for now (both of C65 and MEGA65), and will find its way into dev, then master. So I close it now.

**Closed by lgblgblgb** 2020-12-27 00:11 UTC
Labels: BUG, Committed, target:C65, target:MEGA65

**Comment by sausagejohnson** [comment] 2020-12-29 05:29
Brilliant! Thanks @lgblgblgb

**Comment by lgblgblgb** [comment] 2021-02-10 22:00
It seems we also need to set $82 and $83 as pointers. Thanks to BitShifter for the information.
