### ISSUE TITLE
SDCard config menu caused garbled screen.

### ISSUE THREAD

**Issue by sausagejohnson** [lgblgblgb/xemu#66] opened 2019-01-01 08:18 UTC
Glitch screen error on Linux. Appears when selecting option 2.

This is the normal screen:
![mega65-glitch01](https://user-images.githubusercontent.com/11528721/50571237-21d2cb00-0d9d-11e9-814a-7e6b917c875e.jpg)

This is the result. Appears to be either uninitialised screen graphics, buffer issue perhaps.
![mega65-glitch02](https://user-images.githubusercontent.com/11528721/50571238-26977f00-0d9d-11e9-8571-b486c2b1dd62.jpg)

However by restarting the app and going to option 1:
![mega65-glitch03](https://user-images.githubusercontent.com/11528721/50571242-31521400-0d9d-11e9-872d-8f44c6abbf96.jpg)

Then selecting save and boot for next / ok:
![mega65-glitch04](https://user-images.githubusercontent.com/11528721/50571243-33b46e00-0d9d-11e9-91a0-ea9dbfce3f0a.jpg)

Then selecting option 2 again from the main menu, you get the following correct screen.
![mega65-glitch05](https://user-images.githubusercontent.com/11528721/50571246-3b741280-0d9d-11e9-8747-e313991b10bd.jpg)

**Comment by lgblgblgb** [comment] 2019-01-06 20:42
Yes, I know about this bug, I've also noticed some months ago, or so. Unfortunately I have not too much precise idea what causes it, only wild guesses. But, note, that Xemu's VIC-IV "emulation" is a kind of "almost nothing" and only what is strictly needed to do basically just something. For example the VIC-IV specific pointers for video RAM, font etc, and the method, that writing "legacy" VIC-II or VIC-III registers causes VIC-IV specific registers to be altered. I am somehow a bit concerned that these kind of problems in Xemu or simply the lack of "sane VIC-IV emulation" causes the problem. In fact, sooner or later the whole VIC-IV emulation in Xemu will be rewritten from basically zero, hopefully that can fix this issue too, if we can't find the solution of this problem sooner, of course :) Anyway, thanks for the report! Yes, it's a bug, that's true. However you can find tons of it, some of them simply lack of M65 features in Xemu, some of them are miss-behaves or better called "bug", like in our case.

**Comment by lgblgblgb** [comment] 2019-01-06 20:57
Btw, one important thing: I strongly (surely, I can be wrong) believe that it's nothing to do with the OS (Linux) or SDL but some problem in VIC-IV emulation that wrong memory area is used there by Xemu from the Mega65 RAM as "font memory" or something like this. So, I think it's a VIC-IV related emulation bug, not not a core Xemu thing, like SDL, OS, whatever. I only say this, because how I noticed this bug was the following: I noticed the same thing as you. By pressing F9 to "reset" it works. I am not sure what you mean about "restarting the app", exiting from Xemu and starting again, and even that fixes it? Then I can be wrong with my assumptions, I've described above.

**Comment by sausagejohnson** [comment] 2019-01-06 21:31
I wonder if a temporary workaround would be to automatically navigate the menus and back (it would be fast and probably not noticed) or automatically run the routines under F10 after initialisation?

Yes when I said "restarting the app" I mean quitting out and starting again as a way of reproducing the next steps.

**Comment by lgblgblgb** [comment] 2019-01-06 21:41
Hmm, to be honest, I don't think it worth to introduce an automatized workaround like you describe just for this issue, when this situation is not so common that somebody wants to set-up an SD-card (image) with Xemu:Mega65. It's not even easy to detect when the workaround should be applied, and if it is not automatically done, then we can do "by hand" anyway with F10 etc. The problem is more like when this bug can effect multiple other "more common" things as well. I don't say this is not an important bug, in fact the opposite, it can signal a more serious problem somewhere. I just say that the only actual observation of the bug is kinda a "marginal" thing, and also, not this scenario should be workarounded but the bug which causes this (which then may effect hundreds of things in the future what we can't see now yet, since not so much M65-specific software exists yet currently ...).

**Comment by lgblgblgb** [comment] 2019-01-06 22:21
Btw, try this: in file targets/mega65/mega65.c locate the statement with cia_init(&cia2 ... and after the ); insert this: cia2.DDRA = 3; Honestly, I have no idea why it is a problem, as it should be initialized by the system software ... It's even possible (?) that it has something to do with the SD-card setup software that it does not initialize the DDR register of CIA2 port A, however then it should be buggy on the FPGA board as well (which is not, I've checked). So it's even possible problem with my veeeeery rudimentary CIA "emulation" ... (which selects the VIC-II bank in our case, and as I've debugged now, it seems wrong VIC-II bank is used, that causes the garbage on the screen).

**Comment by lgblgblgb** [comment] 2019-01-07 06:14
I meant entering into setup, F10 then entering into SD-menu, so basically the same as you suggested to exit/save from setup then SD-menu.

**Comment by lgblgblgb** [comment] 2019-01-07 09:09
I meant entering into setup, F10 then entering into SD-menu, so basically the same as you suggested to exit/save from setup then SD-menu.

**Comment by lgblgblgb** [comment] 2019-01-07 17:21
I close this bug, since there is a fix committed by me into the dev branch of Xemu. It's a workaround, and it seems Paul also made a fix into the mega65 project itself for this problem after my explanation on this issue.

**Closed by lgblgblgb** 2019-01-07 17:21 UTC
Labels: BUG, target:MEGA65
