### ISSUE TITLE
MEGA65: Wrong colors and garbled sprites on real hardware for games developed on XEMU (Shallan's competition)

### ISSUE THREAD

**Issue by deftmega** [lgblgblgb/xemu#252] opened 2021-05-19 21:03 UTC
The game MEGADOTS, intended to look like this and looking like this on XEMU:
![Snapshot_20210519_225052](https://user-images.githubusercontent.com/3924427/118883450-87d03680-b8f5-11eb-8dca-28c93d92cde0.jpg)

looks like this on the real hardware - r3 board, bitstream 20210511.00,dc89e20:

![Snapshot_20210519_224913](https://user-images.githubusercontent.com/3924427/118883732-dc73b180-b8f5-11eb-881c-e552e7da28fa.jpg)

Apparently Shallan was able to fix the game by adding these instructions:

lda #$6a
sta $d04e

Here's the diskimage including fixed and original (xemu) version:

[James-megadots.zip](https://github.com/lgblgblgb/xemu/files/6511540/James-megadots.zip)

Another game showing the same symptoms is HITBLOCK:

![Snapshot_20210519_224037](https://user-images.githubusercontent.com/3924427/118883957-28265b00-b8f6-11eb-9ac4-3e84fdfe778a.jpg)
![Snapshot_20210519_224143](https://user-images.githubusercontent.com/3924427/118883962-2a88b500-b8f6-11eb-9d18-84ddc0a36b0a.jpg)
[hitblock65_withsrc.zip](https://github.com/lgblgblgb/xemu/files/6511544/hitblock65_withsrc.zip)

A bit more dramatic is KALLE KLOAKKE. The screen start address seems to be at the wrong place:

![Snapshot_20210519_224333](https://user-images.githubusercontent.com/3924427/118884101-50ae5500-b8f6-11eb-94f6-d4b9cf496f77.jpg)
![Snapshot_20210519_224348](https://user-images.githubusercontent.com/3924427/118884112-55730900-b8f6-11eb-9426-b940e7815ffc.jpg)
[kalle65.zip](https://github.com/lgblgblgb/xemu/files/6511576/kalle65.zip)

**Comment by hernandp** [comment] 2021-05-21 03:14
Working on this now, thanks.

**Comment by hernandp** [comment] 2021-05-21 03:50
Note about **Sprite pointer table address** 

MEGADOTS-XEMU sets sprite pointer table with $D06E-6C to $BF8 but this is read as $BF0  (applied mask for effective address fetch is $8FFFF0).  Official docs were wrong, the correct behavior is specified in https://github.com/MEGA65/mega65-core/issues/339.

**Comment by lgblgblgb** [comment] 2021-05-23 11:40
Dunno if connected, but issue #258 revealed an error that "use ROM palette" bit inverted compared to the real thing. It can also cause colour problems, not sure if it's an issue here (or at least partly) too.

**Comment by lgblgblgb** [comment] 2021-06-05 09:11
I think, these should be retested, as many mods/fixes was done in `merger`, it's hard to know what has been fixed from these issues for now, and what left ...

**Comment by deftmega** [comment] 2021-06-06 19:31
I have retested and got the following results:
1) Hitblock is showing the wrong colors like the hardware now. This is good. "H" from Hitblock is intact tho (expected to be wrong like in hardware).
2) Kalle Kloakke (original version) still works flawlessly (expected to be broken like in hardware).
3) Megadots still work flawlessly (expected to have wrong colors like in hardware).

**Comment by lgblgblgb** [comment] 2021-06-06 21:16
OK. Hitblock seems to be cured in the process of fixing various bugs :) That was part of my original intent to fix "known-problems" which then may fix many things no need to dig further. The other two I have no idea about **yet**, maybe the mentioned `$d04e` problem?

**Comment by lgblgblgb** [comment] 2021-06-08 11:54
@deftmega  Oh, and btw, beware that it's a bit confusing, having two versions now from megadots (for example) then what should be look what, I'm totally confused ;) At least last time I checked megadots, it was OK, that even in Xemu it was that "pink mess", though you states you don't see this.

**Comment by deftmega** [comment] 2021-06-08 14:28
@lgblgblgb pink mess is good! Maybe I confused the versions!

**Comment by lgblgblgb** [comment] 2021-06-08 16:07
@deftmega I am not sure I haven't confused, hehe :)

**Comment by lgblgblgb** [comment] 2021-09-18 09:59
I close this now. In overall there were many fixes etc in Xemu in these regards and the issue is a bit too generic. If certain problems remains, for sure, it should be opened as a specific issue on that given problem.

**Closed by lgblgblgb** 2021-09-18 09:59 UTC
Labels: WIP, target:MEGA65, compatibility-example, VIC-IV
